services:
  neo4j:
    container_name: neo4j_db
    image: neo4j:5.12-community
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: neo4j/hackathon2023
      NEO4J_dbms_default__database: neo4j
    volumes:
      - neo4j_data:/data
      - ./backend/UC6_input_datasetd6889de:/var/lib/neo4j/import

  backend:
    container_name: bnp_backend
    image: abhay41/fund_referential-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - neo4j

  frontend:
    container_name: bnp_frontend
    image: abhay41/fund_referential-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend

volumes:
  neo4j_data:
